CM3035_Final_Proj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('e_learning_application.urls')),
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

chat/urls.py
from django.urls import path, re_path
from .views import chat_room
from . import consumers

urlpatterns = [
   path('room/<int:course_id>/', chat_room, name='chat_room'),
]

e_learning_application/urls.py
from django.urls import include, path
from . import views #--Importing from views.py--//
from . import api   #Importing from api.py---//
from .views import *
from django.conf import settings
from django.conf.urls.static import static
from e_learning_application.views import api_status_update
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView



urlpatterns =[
    path ('', views.index, name='index' ),
    path ('create-new-account/', views.create, name='create'),
    path ('login/', views.user_login, name='login'),
    path ('courses/', views.courses, name='courses'),
    path ('logout/', views.user_logout, name='logout'),
    path('student_dashboard/<int:appUser_id>', views.studentHomepage, name= 'student_dashboard'),
    path('teacher_dashboard/<int:appUser_id>', views.teacherHomepage, name= 'teacher_dashboard'),

    # Dynamic route for viewing a user's homepage
    path('user/<int:appUser_id>/', views.userHomepage, name='user_homepage'),

    path('create-course/', views.create_course, name='create_course'),
    path('delete-course/<int:course_id>/', views.delete_course, name='delete_course'),
    path('add-content/', views.add_content, name='add_content'),
    path('delete-content/<int:content_id>', views.delete_content, name='delete_content'),
    path('enroll/<int:course_id>/', views.enroll_in_course, name='enroll_in_course'),
    path('unenroll/<int:course_id>/', views.unenroll_from_course, name='unenroll_from_course'),
    path('unenroll/<int:course_id>/<int:student_id>', views.removed_from_course, name='removed_from_course'),
    path('course-content/<int:course_id>/', views.course_content, name='course_content'),
    path('search-user/', views.search_user, name='search_user'),
    path('error/', views.error_page, name='error_page'),
    path('status-page/', views.status_page, name='status_page'),
    path('status-form-page/', views.status_form_page, name='status_form_page'),
    path('check-new-status-updates/', check_new_status_updates, name='check_new_status_updates'),

    #---for the chat room---#
    path('chat/', include('chat.urls')), 
    #----Api endpoints----#
    path("api/status-update/", api_status_update, name="api_status_update"),
    # Swagger documentation endpoints
    path("api/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("api/docs/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger-ui"),
] 

e_learning_application/models.py
from django.db import models

# Create your models here.
#-----For setting up user accounts---#
from django.contrib.auth.models import User
#----For setting up contraints for cases where the same user cant enroll into the same course etc-----#
from django.db.models import UniqueConstraint
#----------For error handling----------#
from django.core.exceptions import ValidationError


#---For defining roles choices for my E-Learning applications---#
ROLE_CHOICES = [
    ('Teacher', 'Teacher'),
    ('Student', 'Student'),
]


#____________________________--------Models for the users------------___________________________#

class AppUser(models.Model):
    role = models.TextField(max_length=10, choices=ROLE_CHOICES)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    #---The django User contains the fields username, email, password and id)--#
    #---So they can be accessed via user.username, user.email etc-----# 

    def __str__(self):
        return  f"{self.user.username} ({self.role})"


class Teachers(models.Model):
    teacherID = models.AutoField(primary_key=True)
    userID = models.ForeignKey(AppUser, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        #----Ensure the linked AppUser has the role 'teacher'-----#
        if self.userID.role != 'Teacher':
            raise ValueError("Only users with the role 'Teacher' can be added to the Teachers model.")
        super().save(*args, **kwargs)

    def __str__(self):
        return f"{self.userID.user.username} (Teacher)"
    
class Students(models.Model):
    studentID = models.AutoField(primary_key=True)
    userID = models.ForeignKey(AppUser, on_delete=models.CASCADE)

    def save(self, *args, **kwargs):
        #----Ensure the linked AppUser has the role 'teacher'-----#
        if self.userID.role != 'Student':
            raise ValueError("Only users with the role 'Student' can be added to the Students model.")
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"{self.userID.user.username} (Student)"

#________-----Models for the courses, enrolled courses + feedback for courses-----_________#
class Course(models.Model):
    courseID = models.AutoField(primary_key=True)
    teacherID = models.ForeignKey(Teachers, on_delete=models.SET_NULL, null=True)
    courseTitle = models.TextField(max_length=256, null=False)
    courseDescription = models.TextField(max_length=256, null=False)
    courseCreatedDate = models.DateField(auto_now_add=True)

    def __str__(self):
        return f"Course Title: {self.courseTitle}"


class CourseContent(models.Model):
    contentID = models.AutoField(primary_key=True)
    contentTitle = models.TextField(max_length=256, null=False)
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name="courseContent")
    file = models.FileField(upload_to='course_files/', null=True, blank=True)  #--Field for file uploads--#
    date_added = models.DateTimeField(auto_now_add=True)
    teacher = models.ForeignKey(Teachers, on_delete=models.DO_NOTHING, related_name="teacher")
    #---Note for future use: to access teacher's username = course_content.teacher.userID.user.username--#

    def __str__(self):
        return f"Content for {self.course.courseTitle}"


class Enrollments(models.Model):
    enrollmentID = models.AutoField(primary_key = True)
    courseID = models.ForeignKey(Course, on_delete=models.CASCADE)
    studentID = models.ForeignKey(Students, on_delete=models.CASCADE)
    enrollment_date = models.DateField(auto_now_add=True)
    class Meta:
        constraints = [
            UniqueConstraint(
                #---Ensures unique combination of studentID and courseID----#
                fields=['studentID', 'courseID'],  
                #---Name of the constraint---#
                name='unique_student_course'  
            )
        ]
        
    def __str__(self):
        return f"{self.studentID.userID.user.username} enrolled in {self.courseID.courseTitle}"


class Feedback(models.Model):
    feedbackID = models.AutoField(primary_key = True)
    courseID = models.ForeignKey(Course, on_delete=models.CASCADE)
    studentID = models.ForeignKey(Students, on_delete=models.CASCADE)
    feedbackText = models.TextField(max_length=256, null=False, blank= False)
    date_of_feedback = models.DateField(auto_now_add=True)

    def save(self, *args, **kwargs):
        #---Check if said student is enrolled in said course-------------#
        if not Enrollments.objects.filter(studentID=self.studentID, courseID=self.courseID).exists():
            raise ValidationError("Only enrolled students can submit feedback for this course.")
        super().save(*args, **kwargs)
    
    def __str__(self):
        return f"Feedback by {self.studentID.userID.user.username} for {self.courseID.courseTitle}"



#________----------models for the application's other functionalities----------------__________#
class StatusUpdates(models.Model):
    statusUpdatesId = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(AppUser, on_delete=models.CASCADE)
    status_content = models.TextField(max_length=256, null=False, blank=False)
    status_update_date = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)

    def __str__(self):
        return f"Status update by {self.user_id.user.username} on {self.status_update_date}"



    

e_learning_application/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from django.contrib.auth.models import User
#---for password validation---# 
import re

ROLE_CHOICES = [
    ('Student', 'Student'),
    ('Teacher', 'Teacher'),
]


#---------------form for creating new users------------------#
class UserRegistrationForm(forms.ModelForm):
    role = forms.ChoiceField(
        choices=ROLE_CHOICES,
        widget=forms.Select(attrs={'class': 'form-select'}),
    )
    
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        help_text="Required. 8 Characters minimally. Consisting of at least 1 upper and lower casing letters and digits"
    )

    class Meta:
        model = User
        fields = ['username', 'email', 'password']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
        }

    #---This part is to arrange the order of how the fields are displayed on the page  
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        #---removing the default help text---#
        self.fields['username'].help_text = None

        #---Rearranging the order of the fields--#
        self.fields = {
            'role': self.fields['role'],
            'username': self.fields['username'],
            'email': self.fields['email'],
            'password': self.fields['password'],
        }


    #-----imposing retrictions/criteria for the password-------#
    def clean_password(self):
        password = self.cleaned_data.get('password')

        #---Validating password requirements---#
        if len(password) < 8:
            raise ValidationError("Password must be at least 8 characters long.")
        if not re.search(r'[A-Z]', password):
            raise ValidationError("Password must contain at least one uppercase letter.")
        if not re.search(r'[a-z]', password):
            raise ValidationError("Password must contain at least one lowercase letter.")
        if not re.search(r'\d', password):
            raise ValidationError("Password must contain at least one digit.")

        return password


#----------------form for logging in-------------#
class UserLoginForm(forms.Form):
    role = forms.ChoiceField(label="Login as", choices=ROLE_CHOICES, widget=forms.Select(attrs={'class': 'form-select'}))
    email = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'class': 'form-control'}))
    password = forms.CharField(label="Password", widget=forms.PasswordInput(attrs={'class': 'form-control'}))


#-----form for the courses and courseContent--------#
class CourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = ['courseTitle', 'courseDescription']


class CourseContentForm(forms.ModelForm):
    class Meta:
        model = CourseContent
        fields = ['contentTitle', 'course', 'file']

class FeedbackForm(forms.ModelForm):
    class Meta:
        model = Feedback
        fields = ['feedbackText']

class StatusUpdateForm(forms.ModelForm):
    class Meta:
        model = StatusUpdates
        fields = ['status_content']

e_learning_application/templates/e_learning_application/MainHomepage.html
<!----------The Main homepage --------->

{% extends "./templatePage.html" %}
{% load bootstrap4 %}
{% load static %}

{% block contentSect %} 


<div class="container-fluid mt-5 pb-5 MainHomePageDiv">
    <div class="row align-items-center">
        <!-- Left column of the homepage: Headers and sign up button -->
        <div class="col-md-8">
            <h1 class="MainHomepageHeader">
                <span class="websiteHeaderHi">Hi</span><span class="websiteHeaderLearners">Learners</span>
            </h1>
            <h1 class="MainHomepageSubheader">The best online learning software for you!</h1>
            <!-- Sign Up Button (Visible only on desktop) -->
            <a href="{% url 'create' %}" class="btn HomepageSignUpBtn testBtn mt-5 d-none d-md-inline-block">SIGN UP NOW!</a>
        </div>
        
        <!-- Right column of the homepage: Image(s) -->
        <div class="col-md-4 text-end">
            <img src="{% static 'images/5-star-google-review-request.jpg' %}"  class="img-fluid FiveStarImage" alt="Logo">
        </div>


    </div>
    <!-- Sign Up Button (Visible only on mobile, below the image) -->
    <div class="row d-md-none mt-3">
        <div class="col text-center">
            <a href="{% url 'create' %}" class="btn HomepageSignUpBtn">SIGN UP NOW!</a>
        </div>
    </div>

</div>


{% endblock %}

e_learning_application/templates/e_learning_application/StudentHomepage.html
{% extends "./templatePage.html" %}
{% load bootstrap4 %}
{% load static %}

{% block contentSect %} 

<div class="container-fluid mt-5 pb-5 text-center ">
    <h1> Courses <span class="accountUsername"> {{ appUser.user.username }} </span> enrolled in:</h1>
</div>

{% if enrolled_courses %}
    <div class="container-fluid"> 
        <div class="row justify-content-center"> 
            {% for course in enrolled_courses %}
                <div class="col-md-4 mb-4 d-flex justify-content-center">
                    <div class="card courseCard" >
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ course.courseTitle }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary pt-1 "> Created by: {{ course.teacherID.userID.user.username }} </h6>
                            <h6 class="card-subtitle mb-2 text-body-secondary pt-1 "> Created date: {{ course.courseCreatedDate }} </h6>
                            <p class="card-text"> {{ course.courseDescription }} </p>
                            <a href="{% url 'course_content' course.courseID %}" class="card-link btn courseEditBtn"> View course </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% else %}
    <hr class="sepratorLine">
    <h2 class="text-center pt-5 pb-5">No courses have been created yet</h2>
    <hr class="sepratorLine">
{% endif %}



{% if status_list %}
<div class="container">
    <h2 class="mt-4 text-center pb-2"> Lastest Status Updates by <span class="accountUsername"> {{ appUser.user.username }} </span> </h2>
    <ul class="list-group">
        {% for status in status_list %}
            <li class="list-group-item d-flex justify-content-between statusLi">
                <span>{{ status.status_content }}</span>
                <small class="text-muted">{{ status.status_update_date }}</small>
            </li>
        {% endfor %}
    </ul>
</div>
{% else %}
    <hr class="sepratorLine">
    <h2 class="text-center pt-5 pb-5">No updates have been made recently</h2>
    <hr class="sepratorLine">
{% endif %}

{% endblock %}

e_learning_application/templates/e_learning_application/TeacherHomepage.html
{% extends "./templatePage.html" %}
{% load bootstrap4 %}
{% load static %}
{% block contentSect %} 

<div class="container-fluid mt-5 pb-5 text-center ">
    <h1> Courses created by: <span class="accountUsername"> {{ appUser.user.username }} </span> </h1>
</div>


{% if teacher_courses %}
    <div class="container-fluid">
        <div class="row justify-content-center"> 
            {% for course in teacher_courses %}
                <div class="col-md-4 mb-4 d-flex justify-content-center">
                    <div class="card courseCard" >
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ course.courseTitle }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary pt-1 "> Created by: {{ course.teacherID.userID.user.username }} </h6>
                            <h6 class="card-subtitle mb-2 text-body-secondary pt-1 "> Created date: {{ course.courseCreatedDate }} </h6>
                            <p class="card-text"> {{ course.courseDescription }} </p>
                            <a href="{% url 'course_content' course.courseID %}" class="card-link btn courseEditBtn"> View/edit course </a>
                            <a href="{% url 'delete_course' course.courseID %}" class="card-link btn courseEditBtn"> Delete course </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% else %}
<hr class="sepratorLine">
<h2 class="text-center pt-5 pb-5">No courses have been created yet</h2>
<hr class="sepratorLine">
{% endif %}

<!-- So that outsiders can't tamper with this: Only this account's users can have access to these buttons-->
{% if request.user.appuser.id == appUser.id %}
    <div class="container-fluid mt-5 pb-5 d-flex justify-content-center d-none d-md-flex">
        <div class="createCourseBtnSect">
            <a href="{% url 'create_course' %}" class="btn createCourseBtn d-none d-md-inline-block">Create new course</a>
        </div>
        <div>
            <a href="{% url 'add_content' %}" class="btn createContentBtn d-none d-md-inline-block">Add in new learning material</a>
        </div>
    </div>
    <div class="d-md-block d-lg-none d-flex flex-column align-items-center">
        <a href="{% url 'create_course' %}" class="btn createCourseBtn d-block mb-3">Create new course</a>
        <a href="{% url 'add_content' %}" class="btn createContentBtn d-block">Add in new learning material</a>
    </div>
{% endif %}



{% if status_list %}
<div class="container">
    <h2 class="mt-4 text-center pb-2"> Lastest Status Updates by <span class="accountUsername"> {{ appUser.user.username }} </span> </h2>
    <ul class="list-group">
        {% for status in status_list %}
            <li class="list-group-item d-flex justify-content-between statusLi">
                <span>{{ status.status_content }}</span>
                <small class="text-muted">{{ status.status_update_date }}</small>
            </li>
        {% endfor %}
    </ul>
</div>
{% else %}
    <hr class="sepratorLine">
    <h2 class="text-center pt-5 pb-5">No updates have been made recently</h2>
    <hr class="sepratorLine">
{% endif %}


{% endblock %}

e_learning_application/templates/e_learning_application/addContent.html
{% extends "./templatePage.html" %}
{% load static %}

{% block contentSect %}
<div class="container mt-5">
    <div class="card p-4">
        <h2 class="text-center">Add in Lesson content</h2>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="w-100 d-flex flex-column align-items-center"> 
                
                <div class="mb-3 pt-3 text-center">
                    <label for="{{ content_form.contentTitle.id_for_label }}" class="form-label">Title of the new learning material:</label>
                    <div class="text-center">
                        {{ content_form.contentTitle }}
                    </div>
                </div>

                <div class="mb-3 pt-3">
                    <label for="{{ content_form.course.id_for_label }}" class="form-label"> Which course is this learning material for? </label>
                    <div class="text-center">
                        {{ content_form.course }}
                    </div>
                </div>

                <div class="mb-3 w-100 text-center pt-3 pb-5">
                    <label for="{{ content_form.file.id_for_label }}" class="form-label answerFormCheckmark"> Add in file content</label>
                    <div class="d-flex justify-content-center contentFileInput text-center">
                        {{ content_form.file }}
                    </div>
                </div>

                <button type="submit" class="btn genericButton"> Update course content </button>

            </div>
        </form>
    </div>
</div>

{% endblock %}

e_learning_application/templates/e_learning_application/courses.html
{% extends "./templatePage.html" %}
{% load static %}


{% block contentSect %} 
<div class="container-fluid mt-5 pb-5 text-center ">
    <h1> Our Available Courses!</h1>
</div>
{% if available_courses %}
    <div class="container-fluid">
        <div class="row justify-content-center"> 
            {% for course in available_courses %}
                <div class="col-md-4 mb-4 d-flex justify-content-center">
                    <div class="card courseCard" >
                        <div class="card-body text-center">
                            <h5 class="card-title">{{ course.courseTitle }}</h5>
                            <h6 class="card-subtitle mb-2 text-body-secondary pt-1 "> Created by: {{ course.teacherID.userID.user.username }} </h6>
                            <h6 class="card-subtitle mb-2 text-body-secondary pt-1 "> Created date: {{ course.courseCreatedDate }} </h6>
                            <p class="card-text"> {{ course.courseDescription }} </p>
                            <!-- passing in the corresponding course id when the enroll btn is clicked on -->
                            <a href="{% url 'enroll_in_course' course.courseID %}" class="card-link btn courseEnrollBtn"> Enroll </a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endif %}

{% if user.is_authenticated %}

{% else %}
    <div class="container-fluid d-flex justify-content-center align-items-center">
        <a href="{% url 'create' %}" class="btn HomepageSignUpBtn mt-5">SIGN UP NOW!</a>
    </div>
{% endif %}

{% endblock %}

e_learning_application/templates/e_learning_application/create.html
{% extends "./templatePage.html" %}
{% load bootstrap4 %}
{% load static %}

{% block contentSect %} 

<div class="container-fluid createSect align-items-center d-flex justify-content-center align-items-center ">
    <div class="card createCard text-center" >
      
        <div class="card-body">
          <h5 class="card-title createCardTitle">Create your account</h5>
          <!-- <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
          <a href="#" class="btn btn-primary">Go somewhere</a> -->

          <form method="POST">
            {% csrf_token %}

            <!-- Loop through form fields to render them -->
            {% for field in form %}
            <div class="mb-3">
              <div class="d-flex align-items-center justify-content-between">
                <!-- The field's label/ is this email, role or password? etc -->
                <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>

                <!-- Error messages -->
                {% if field.errors %}
                    <div class="error-message">
                        {% for error in field.errors %}
                            <p>{{ error }}</p>
                        {% endfor %}
                    </div>
                {% endif %}                
              </div>

              {{ field }}
                
              <!-- Help text (e.g., password requirements) -->
              {% if field.help_text %}
                  <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}

            </div>
            {% endfor %}

            <button type="submit" class="btn genericButton">Create new account</button>
          </form>

        </div>
    </div>
</div>


{% endblock %}

e_learning_application/templates/e_learning_application/createCourses.html
{% extends "./templatePage.html" %}
{% load static %}

{% block contentSect %} 


<div class="container createCourseContainer mt-5">
    <div class="card p-4">
        <h2 class="text-center pb-3">Create a New Course</h2>
        <form method="POST">
            {% csrf_token %}
            <div class="w-100 d-flex flex-column align-items-center"> 
                <div class="mb-3">
                    <label for="{{ course_form.courseTitle.id_for_label }}" class="form-label">Course Title</label>
                    <div>
                        {{ course_form.courseTitle }}
                    </div>
                </div>
            
                <div class="mb-3">
                    <label for="{{ course_form.courseDescription.id_for_label }}" class="form-label">Course Description</label>
                    <div>
                        {{ course_form.courseDescription }}
                    </div>
                </div>
                <button type="submit" class="btn genericButton">Create Course</button>
            </div>

        </form>
    </div>
</div>

{% endblock %}

e_learning_application/templates/e_learning_application/errorPage.html
{% extends "./templatePage.html" %}
{% load static %}

{% block contentSect %} 

<div class="container-fluid text-center pt-5 pb-5">
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-danger alertMessage">{{ message }}</div>
        {% endfor %}
    {% endif %}
    <h2>Access Denied</h2>
    <p>You do not have permission to view this page.</p>
    <a href="{% url 'index' %}" class="btn genericButton pt-2">Go Back Home</a>
</div>
{% endblock %}

e_learning_application/templates/e_learning_application/searched_results.html
{% extends "./templatePage.html" %}
{% load static %}

{% block contentSect %} 

<div class="container-fluid mt-5 pb-5 text-center ">
    <h1> Searched Results for: <span class="generic_span">  {{ query }} </span> </h1>
</div>


<div class="table-responsive ">
    <table class="table table-striped table-bordered table-dark mt-4 searchedTable">
        <thead class="thead-dark">
            <tr >
                <th scope="col" class="text-center align-middle">#</th>
                <th scope="col" class="text-center align-middle">Username</th>
                <th scope="col" class="text-center align-middle">Email</th>
                <th scope="col" class="text-center align-middle">Role</th>
                <th scope="col" class="text-center align-middle">Course(s) user is enrolled in</th>
                <th scope="col" class="text-center align-middle">Course(s) user has created</th>
            </tr>
        </thead>

        <tbody>
            {% for user in searched_users %}
            <tr>
                <td class="text-center align-middle" >{{ forloop.counter }}</td>
                <td class="text-center align-middle" >
                    <!-- Ensures that the teacher can viewed the searched user's homepage -->
                    <a href="{% url 'user_homepage' user.id %}" 
                    class="card-link btn genericButton searchedUserBtn"> 
                        {{ user.user.username }}
                    </a>
                </td>
                <td class="text-center align-middle" >{{ user.user.email }}</td>
                <td class="text-center align-middle" >{{ user.role }}</td>
                <!-- Displays all of the courses that the user has enrolled in -->
                {% if user.role == "Student" %}
                    <td class="text-center align-middle">  
                        {% with student=user.students_set.all.0 %}
                            {% if student and student.enrollment_list %}
                                <ul class="list-unstyled">
                                    {% for enrollment in student.enrollment_list %}
                                        <li>{{ enrollment.courseID.courseTitle }}</li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                None
                            {% endif %}
                        {% endwith %}
                    </td>
                    <td class="text-center align-middle" >
                        None
                    </td>
                <!-- Displays all of the courses that the user has created in -->
                {% elif user.role == "Teacher" %}
                    <td class="text-center align-middle" >
                        None
                    </td>                
                
                    <td class="text-center align-middle" >
                        {% with teacher=user.teachers_set.all.0 %}
                            {% if teacher and teacher.created_courses_list %}
                                <ul class="list-unstyled">
                                    {% for course in teacher.created_courses_list  %}
                                        <li>{{ course.courseTitle }}</li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                None
                            {% endif %}
                        {% endwith %}
                    </td>
                {% endif %}

            </tr>
            {% empty %}
            <tr class="text-center align-middle">
                <td colspan="6" class="text-center">No such user was found.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

{% endblock %}

e_learning_application/templates/e_learning_application/statusForm.html
{% extends "./templatePage.html" %}
{% load bootstrap4 %}
{% load static %}

{% block contentSect %} 

<div class="container-fluid mt-5 pb-5 text-center ">
    <h1> Post your own status updates!</h1>
</div>

<form method="POST">
    {% csrf_token %}
    <div class="w-100 d-flex flex-column align-items-center"> 
        <div class="mb-3">
            <label for="{{ status_form.status_content.id_for_label }}" class="form-label">Status text:</label>
            <div>
                {{ status_form.status_content }}
            </div>
        </div>

        <button type="submit" class="btn genericButton">Create Status Update</button>
    </div>

</form>



{% endblock %}

e_learning_application/templates/e_learning_application/statusPage.html
{% extends "./templatePage.html" %}
{% load bootstrap4 %}
{% load static %}

{% block contentSect %} 
<div class="container">
    <h2 class="mt-4 text-center pb-2">All Of Your Status Updates</h2>
    <ul class="list-group">
        {% for status in status_list %}
            <li class="list-group-item d-flex justify-content-between statusLi">
                <span>{{ status.status_content }}</span>
                <small class="text-muted">{{ status.status_update_date }}</small>
            </li>
        {% empty %}
            <li class="list-group-item text-muted">No updates yet.</li>
        {% endfor %}
    </ul>
    <div class="text-center pt-5">
        <a href="{% url 'status_form_page' %}" class="btn statusUpdateBtn ">Add in your own status update!</a>
    </div>
</div>





{% endblock %}

e_learning_application/templates/e_learning_application/templatePage.html
<!----------The base template for all of the pages--------->

{% include "e_learning_application/header.html" %}

{% block contentSect %} 

<h1> Template is rendered</h1>

{% endblock %}

{% include "e_learning_application/footer.html" %}